name: fe_pathpal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.5.0

dependencies:
   convert: ^3.1.1
   curved_navigation_bar: ^1.0.6
   fl_chart: ^0.68.0
   flutter:
      sdk: flutter
   http: ^1.2.2
   lottie: ^3.1.2
   pedometer: ^4.0.2
   shared_preferences: ^2.3.2
   flutter_3d_controller: ^1.3.1

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/shiba.glb
