name: pathpal
description: "An interesting lifestyle app."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.5.0

dependencies:
   flutter:
      sdk: flutter
   model_viewer_plus: ^1.8.0
   moon_design: ^1.0.3
   pedometer: ^4.0.2
   url_launcher: ^6.1.5

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/shiba.glb
      - assets/shiba.usdz
