name: fe_pathpal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.5.0

dependencies:
   convert: ^3.1.1
   flutter:
      sdk: flutter
   http: ^1.2.2
   pedometer: ^4.0.2

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true
