name: pathpal
description: "An interesting lifestyle app."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.5.0

dependencies:
   convert: ^3.1.1
   dio: ^5.6.0
   fl_chart: ^0.68.0
   flutter:
      sdk: flutter
   http: ^1.2.2
   model_viewer_plus: ^1.8.0
   pedometer: ^4.0.2
   shared_preferences: ^2.3.2
   syncfusion_flutter_gauges: ^26.2.10
   url_launcher: ^6.1.5

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/shiba.glb
      - assets/shiba.usdz
